targets:
  $default:
    builders:

      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
