name: space_x_test_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  bloc: ^9.0.1
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  mockito: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:

  uses-material-design: true
